name: Image exists
description: Checks if a docker image exists
outputs:
  is_not:
    description: true when the image cannot be found in github package registry, false if not
runs:
  using: node12
  main: dist/index.js
